### ISSUE TITLE
Enter not working to insert Gist

### ISSUE THREAD

**Issue by patrickgilmour** [aki77/atom-gist#1]
atom-gist is listing my gists perfectly. I can Edit, Delete and View in browser without an issue.
But I can't Insert. When I select a gist and press 'enter', nothing happens - the gist isn't inserted.

**Comment by aki77** [comment]
Please post screenshot.

[![Gyazo](https://i.gyazo.com/b347353bbc337db13ea3fabb8dc8a943.png)](https://gyazo.com/b347353bbc337db13ea3fabb8dc8a943)

**Comment by patrickgilmour** [comment]
Thanks - here is the screenshot for the enter keybindings:

![atom-gist-keybindings](https://cloud.githubusercontent.com/assets/2692797/9340991/3170062e-45c1-11e5-8493-128ae7f5b8e5.png)

**Comment by aki77** [comment]
What displays in the keybinding resolver when you press that keybinding? `enter`

[![Gyazo](https://i.gyazo.com/58d16ef787736c030d95f76d751a569a.gif)](https://gyazo.com/58d16ef787736c030d95f76d751a569a)

**Comment by patrickgilmour** [comment]
Thanks for your on-going help. I see the attached.
![resolver](https://cloud.githubusercontent.com/assets/2692797/9458046/b6557db0-4ab7-11e5-8c47-65c476221ccd.png)

**Comment by aki77** [comment]
Please post url of gist which can't be inserted.

**Comment by patrickgilmour** [comment]
Example of a gist that won't insert: https://gist.github.com/patrickgilmour/a107ef95020574b8388a

**Comment by aki77** [comment]
Please try the latest version.

**Comment by patrickgilmour** [comment]
Looking good - many thanks!

**Comment by aki77** [comment]
:smiley:
