### ISSUE TITLE
Setting don't appear in Settings view

### ISSUE THREAD

**Issue by danielbayley** [aki77/atom-gist#12]
Maybe a regression of #2? I’m having the same issue; the options don’t show up in Settings view at all…

![img](https://cloud.githubusercontent.com/assets/7797479/12586306/ad5e8d0a-c447-11e5-8852-5a2b3a9359e9.png)

I can manually put `gist: environmentName: "GITHUB_TOKEN"` into `config.cson`, and the package then works, but Settings view still doesn't match the [README screenshot](https://github.com/aki77/atom-gist/#settings), so something is amiss…

![img](https://cloud.githubusercontent.com/assets/7797479/12586340/cb7474d0-c447-11e5-82d9-dea34ede8183.png)

**Comment by aki77** [comment]
https://github.com/atom/atom/issues/10426

**Comment by aki77** [comment]
Please try the latest version.

**Comment by danielbayley** [comment]
Fixed. :sunglasses:
