### ISSUE TITLE
Closing gist when saving

### ISSUE THREAD

**Issue by the-glima** [aki77/atom-gist#17]
When I edit my gist and save it closes the tab, then If I want to edit again I have to open the gist in the list.

The preferred behavior it is to maintain the gist tab open when saving.

**Comment by Dayjo** [comment]
@gabrihellmateus Assuming you're using the latest version, this is an option in the settings; 
![image](https://cloud.githubusercontent.com/assets/1255512/15817434/de4730da-2bcf-11e6-84fb-73638679e65f.png)

**Comment by aki77** [comment]
@Dayjo Thanks!
