### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by anthonyalvarez** [aki77/atom-gist#25]
What are setup instructions to use this this plugin? 

Getting error message after installation: 

`"Error: required token"`

Assume it is talking about Personal Access Token (PAT), is that right?
Can a single PAT be used across multiple plugin?
Is it better to create a unique PAT for each plugin?

Thank you.

**Comment by aki77** [comment]
Please set token with reference to the following.
https://github.com/aki77/atom-gist#personal-access-tokens
