### ISSUE TITLE
Issue with storing Github PAT in settings.json

### ISSUE THREAD

**Issue by wadehammes** [aki77/atom-gist#29]
Using this package alongside the `sync-settings` package, which stores your Atom settings in Gists for easy sharing between multiple Atom environments, can cause your Github Personal Access Token to be visible publicly since it is stored in Atom's `setting.json`.

After setting up this package today, I got a email from Github saying a PAT of mine was visible in a public gist (aka my `sync-settings` files), and they revoked it.

Not sure what you can do to circumvent this, but wanted to bring to your attention anyways.

**Comment by aki77** [comment]
Thanks!
Please refer to the following readme.
https://github.com/aki77/atom-gist#personal-access-tokens

**Comment by wadehammes** [comment]
That doesn't tell me anything about the issue I just told you.

**Comment by aki77** [comment]
Please use `tokenFile` or `environmentName` settings.
It is not saved in setting.json.
