### ISSUE TITLE
Allow continued editing after save

### ISSUE THREAD

**Issue by spikeheap** [aki77/atom-gist#3]
I often save files I'm working on through habit, but when I'm editing a gist saving the file causes it to close.

To reproduce:
1. Open the gist list
2. Select a gist
3. Press `tab`
4. Select `Edit`
5. Make some changes
6. Press `⌘-S`
7. The gist is saved and closed

I can see why the close-on-save behaviour would exist, and it's also quite useful for me. A config option could work well to preserve the existing behaviour but also allow close-on-save. What do you think?

**Comment by eddvdm** [comment]
+1
Thank you very much for the package but I don't think auto-anything is a good idea unless it's configurable.

**Comment by Dayjo** [comment]
+1
Yeah kinda annoying when it closes, I like to save and send to people while I work on other parts of a Gist. This would make a great option!

If I could get a grasp of coffee script, I'd give it a bash but it looks so alien to me.
